# load("@parser_dependencies//:requirements.bzl", "requirement")
# load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

# py_binary(
#     name = "tcpdump_parser",
#     srcs = ["tcpdump_parser.py"],
#     python_version = "PY3",
#     deps = [
#         requirement("scapy"),
#     ],
# )

