cc_binary(
    name = "interface_edge_counter",
    srcs = ["interface_edge_counter.cc"],
    deps = [
        "//external:glog",
        "//external:gflags",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse", 
    ],
)
