
cc_binary(
    name = "unique_interface_counter",
    srcs = ["unique_interface_counter.cc"],
    deps = [
        "//external:glog",
        "//external:gflags",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse", 
        "//flashroute:dump_result",
        "//flashroute:address",
    ],
)
