load("@parsers_deps//:requirements.bzl", "requirement")

py_binary(
    name = "continuous_runner",
    srcs = ["continuous_runner.py"],
    python_version = "PY3",
    deps = [
        requirement("glog")
    ],
)

py_binary(
    name = "discovery_optimize_mode_runner",
    srcs = ["discovery_optimize_mode_runner.py"],
    python_version = "PY3",
    deps = [
        requirement("glog")
    ],
)